#!/bin/bash

RED=$(tput setaf 1; tput bold)
NORMAL=$(tput sgr0)

errors=$(invoke check-code-style --path .)
message="PEP8 VIOLATIONS"

if [[ $errors ]]; then
  echo -e "$RED$message$NORMAL"
  echo "$errors"
  exit 1
fi
