version: '3.7'

volumes:
  ipython_history: {}

services:
  postgres:
    image: library/postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
      image: redis:6.2.1
      ports:
        - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.8.14
    ports:
      - "5672:5672"