# Generated by Django 3.1.6 on 2021-03-18 02:57

from django.core.management import call_command
from django.db import migrations


def sync_categories(apps, schema_editor):
    call_command('sync_categories_from_file_to_db')


def clear_categories(apps, schema_editor):
    Category = apps.get_model('marketplace', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(sync_categories, clear_categories),
    ]
